name: Update PR
on:
  workflow_run:
    workflows: [ "Visual CI" ]
    types:
      - completed

env:
  NAME: ${{ github.event.number || github.sha }}

jobs:
  update-pr:
    name: Generate Visual CI Artifacts
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 5
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          number: ${{ github.event.number }}
          message: |
            Comparison: <https://protomaps.github.io/basemaps/ci/?left=${{ github.event.pull_request.base.sha }}&right=${{ env.NAME }}>
