name: Visual CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NAME: ${{ github.event.number || github.sha }}

jobs:
  visual-ci:
    name: Generate Visual CI Artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v2
        with:
          path: tiles/data/sources
          key: tiles-data-sources-1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Store artifacts'
        run: |
          mkdir artifacts
          echo "${{ github.event.pull_request.base.sha }}" > artifacts/base_sha
          echo "${{ github.sha }}" > artifacts/branch_sha
          echo "${{ github.event.number }}" > artifacts/pull_request_number
      - run: npm install && npm run --silent generate-layers > artifacts/light.json
        working-directory: base
      - run: |
          mvn --batch-mode -no-transfer-progress -DskipTests package
        working-directory: tiles
      # the osm-earth-water-bounds should match the input .osm.pbf.
      - run: |
          java -Xms4g -Xmx4g -jar target/*-with-deps.jar --area=taiwan --force --download --keep-unzipped --bounds=-180,-85,180,85 --osm-earth-water-bounds=118.1036,20.72799,122.9312,26.60305
        working-directory: tiles
      - run: mv tiles/taiwan.pmtiles artifacts/smalltestregion_vector.pmtiles
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts
